name: MSDO
on:
  push:
    branches:
      - main
# Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: ["main"]
  
jobs:
  sample:
    name: Microsoft Security DevOps

    # Windows and Linux agents are supported
    runs-on: windows-latest

    permissions:
      contents: read
      id-token: write
      actions: read
      # Write access for security-events is useful for uploading findings (GHAS)
      security-events: write
    
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v3
        with:
          # full history is important for some secret scanners to detect historical secrets
          fetch-depth: 0
    
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@latest
        id: msdo
        # with:
        #  config: ...
        #  policy: ...
        #  categories: ...
        #  languages: ...
        #  tools: ...
    
      - name: Run Gitleaks secret scan
        uses: zricethezav/gitleaks-action@v2
        id: gitleaks
        with:
          # detect mode scans repo and writes a report
          args: detect --source=. --report-path=gitleaks-report.json --redact
        env:
          # GITHUB_TOKEN is provided by Actions automatically; the action will use it if needed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload gitleaks report as artifact
        # Updated to actions/upload-artifact@v4 because v3 is deprecated
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

      - name: Fail workflow if secrets were found (optional)
        if: steps.gitleaks.outputs.exit_code != '' && steps.gitleaks.outputs.exit_code != '0'
        run: |
          echo "Gitleaks detected secrets. See artifact 'gitleaks-report' for details."
          # Uncomment the next line to fail the run on any findings
          # exit 1
